/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiDocGenerator: typeof import('./components/ApiDocGenerator/index.vue')['default']
    CodePreview: typeof import('./components/common/CodePreview.vue')['default']
    DataSubmitGenerator: typeof import('./components/dataSubmitGenerator/index.vue')['default']
    DeletedGenerator: typeof import('./components/deletedGenerator/index.vue')['default']
    Demo: typeof import('./components/demo/index.vue')['default']
    Demo1: typeof import('./components/demo1/index.vue')['default']
    Demo2: typeof import('./components/demo2/index.vue')['default']
    Demo3: typeof import('./components/demo3/index.vue')['default']
    Demo4: typeof import('./components/demo4/index.vue')['default']
    Demo5: typeof import('./components/demo5/index.vue')['default']
    Demo6: typeof import('./components/demo6/index.vue')['default']
    Demo7: typeof import('./components/demo7/index.vue')['default']
    ExcelExport: typeof import('./components/ExcelExport/index.vue')['default']
    ExcelFrontImport: typeof import('./components/ExcelFrontImport/index.vue')['default']
    ExcelImport: typeof import('./components/ExcelImport/index.vue')['default']
    FlycodeExport: typeof import('./components/flycodeExport/index.vue')['default']
    FlycodeImport: typeof import('./components/flycodeImport/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MacVideo: typeof import('./components/macVideo/index.vue')['default']
    Menu: typeof import('./components/Menu/index.vue')['default']
    MenuNew: typeof import('./components/MenuNew/index.vue')['default']
    MenuOld: typeof import('./components/MenuOld/index.vue')['default']
    MonacoEnhance: typeof import('./components/MonacoEnhance/index.vue')['default']
    MonacoProvider: typeof import('./components/monacoProvider/index.vue')['default']
    Otaku: typeof import('./components/Otaku/index.vue')['default']
    PrettierFormat: typeof import('./components/prettierFormat/index.vue')['default']
    QueryGenerator: typeof import('./components/queryGenerator/index.vue')['default']
    SaveProtocolWatch: typeof import('./components/common/saveProtocolWatch.vue')['default']
    Theme: typeof import('./components/Theme/index.vue')['default']
  }
}
